[[pages]]
path = "pages/pib.py"
name = "PIB"
icon = "ğŸ“Š"

[[pages]]
path = "pages/populacao.py"
name = "PopulaÃ§Ã£o"
icon = "ğŸ‘¥"

[[pages]]
path = "pages/desemprego.py"
name = "Desemprego"
icon = "ğŸ“‰"

[[pages]]
path = "pages/desigualdade.py"
name = "Desigualdade"
icon = "âš–ï¸"

[[pages]]
path = "pages/renda.py"
name = "Renda"
icon = "ğŸ’°"

[[pages]]
path = "pages/inflacao.py"
name = "InflaÃ§Ã£o"
icon = "ğŸ’¸"

[[pages]]
path = "pages/juros.py"
name = "Juros"
icon = "ğŸ“ˆ"

[[pages]]
path = "pages/credito.py"
name = "CrÃ©dito"
icon = "ğŸ’³"

[[pages]]
path = "pages/cambio.py"
name = "CÃ¢mbio"
icon = "ğŸ’±"

[[pages]]
path = "pages/educacao.py"
name = "EducaÃ§Ã£o"
icon = "ğŸ“š"

[[pages]]
path = "pages/confianca.py"
name = "ConfianÃ§a"
icon = "ğŸ‘"

[[pages]]
path = "pages/energia.py"
name = "Energia"
icon = "âš¡"
